import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:firebase_core/firebase_core.dart'; // ✅ Firebase core
import 'firebase_options.dart'; // ✅ Generated by flutterfire CLI
import 'package:zentra_0/Controllers/auth_controller.dart';
import 'package:zentra_0/Controllers/theme_controller.dart';
import 'package:zentra_0/Controllers/product_controller.dart';
import 'package:zentra_0/Controllers/cart_controller.dart';
import 'package:zentra_0/Controllers/order_controller.dart';
import 'package:zentra_0/Controllers/wishlist_controller.dart';
import 'package:zentra_0/Controllers/user_profile_controller.dart';
import 'package:zentra_0/Controllers/address_controller.dart';
import 'package:zentra_0/Controllers/payment_method_controller.dart';
import 'package:zentra_0/Utils/app_themes.dart';
import 'package:zentra_0/view/splash_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize local storage
  await GetStorage.init();

  // Initialize controllers
  Get.put(ThemeController());
  Get.put(AuthController());
  Get.put(ProductController());
  Get.put(CartController());
  Get.put(OrderController());
  Get.put(WishlistController());
  Get.put(UserProfileController());
  Get.put(AddressController());
  Get.put(PaymentMethodController());

  runApp(const MyApp());
}

// lib/main.dart (Updated MyApp)

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // We already initialized the AuthController in main
    final themeController = Get.find<ThemeController>();

    return GetMaterialApp(
      title: 'Zentra',
      theme: AppThemes.light,
      darkTheme: AppThemes.dark,
      themeMode: themeController.theme,
      defaultTransition: Transition.fade,
      debugShowCheckedModeBanner: false,

      // OPTIONAL: If using the traditional GetX routing structure,
      // you might wrap the content, but since your AuthController uses
      // Get.offAll() in the _routeToInitialScreen method,
      // the existing setup is already efficient.
      home: SplashScreen(),
    );
  }
}
